# Generated by Django 4.2.8 on 2024-01-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ePortal', '0003_rename_message_notification_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
    ]
