# Generated by Django 4.2.8 on 2024-01-11 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ePortal', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
