# Generated by Django 4.2.8 on 2024-01-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ePortal', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
