# Generated by Django 4.2.8 on 2024-01-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ePortal', '0014_personalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='birth_date',
            field=models.CharField(max_length=100),
        ),
    ]
