# Generated by Django 4.2.8 on 2024-01-12 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ePortal', '0016_etatinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korekta', models.CharField(max_length=1000)),
                ('kwota', models.CharField(max_length=10000)),
                ('data_wyp', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ListaPlac',
        ),
    ]
